/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IConverter,
  IConverterInterface,
} from "../../interfaces/IConverter";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IERC20",
        name: "source",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "contract IERC20",
        name: "target",
        type: "address",
      },
    ],
    name: "convert",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IERC20",
        name: "source",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "contract IERC20",
        name: "target",
        type: "address",
      },
    ],
    name: "estimateConvert",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IConverter__factory {
  static readonly abi = _abi;
  static createInterface(): IConverterInterface {
    return new utils.Interface(_abi) as IConverterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IConverter {
    return new Contract(address, _abi, signerOrProvider) as IConverter;
  }
}
