/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  InitializationContext,
  InitializationContextInterface,
} from "../../../../contracts/warper/utils/InitializationContext";

const _abi = [
  {
    inputs: [],
    name: "ContractIsAlreadyInitialized",
    type: "error",
  },
  {
    inputs: [],
    name: "ContractIsNotInitializing",
    type: "error",
  },
];

export class InitializationContext__factory {
  static readonly abi = _abi;
  static createInterface(): InitializationContextInterface {
    return new utils.Interface(_abi) as InitializationContextInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): InitializationContext {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as InitializationContext;
  }
}
