/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IUniverseRegistry__factory } from "./IUniverseRegistry__factory";
export { IUniverseToken__factory } from "./IUniverseToken__factory";
export { UniverseRegistry__factory } from "./UniverseRegistry__factory";
export { UniverseToken__factory } from "./UniverseToken__factory";
