/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as assetRentability from "./asset-rentability";
export type { assetRentability };
import type * as availabilityPeriod from "./availability-period";
export type { availabilityPeriod };
import type * as rentalFeePremium from "./rental-fee-premium";
export type { rentalFeePremium };
import type * as rentalPeriod from "./rental-period";
export type { rentalPeriod };
