import { BlockchainProvider } from '@iqprotocol/abstract-blockchain';

export const mockBlockchainProvider: jest.Mocked<BlockchainProvider> = {
  borrow: jest.fn(),
  estimateLoan: jest.fn(),
  connect: jest.fn(),
  addLiquidity: jest.fn(),
  deployEnterprise: jest.fn(),
  getAccountState: jest.fn(),
  getChainId: jest.fn(),
  getERC20Metadata: jest.fn(),
  getERC721Metadata: jest.fn(),
  getEnterpriseInfo: jest.fn(),
  getLiquidityAllowance: jest.fn(),
  getLiquidityTokenAddress: jest.fn(),
  getLiquidityTokenMetadata: jest.fn(),
  getServiceInfo: jest.fn(),
  getServices: jest.fn(),
  registerService: jest.fn(),
  setLiquidityAllowance: jest.fn(),
  decreaseLiquidity: jest.fn(),
  getBorrowTokenAddress: jest.fn(),
  getBorrowTokenMetadata: jest.fn(),
  getInterestTokenAddress: jest.fn(),
  getInterestTokenIds: jest.fn(),
  getInterestTokenMetadata: jest.fn(),
  getLiquidityInfo: jest.fn(),
  getTokenBalance: jest.fn(),
  increaseLiquidity: jest.fn(),
  removeLiquidity: jest.fn(),
};
