/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IAvailabilityPeriodMechanics,
  IAvailabilityPeriodMechanicsInterface,
} from "../../../../warper/mechanics/availability-period/IAvailabilityPeriodMechanics";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "currentTime",
        type: "uint256",
      },
      {
        internalType: "uint32",
        name: "availabilityPeriodStart",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "availabilityPeriodEnd",
        type: "uint32",
      },
    ],
    name: "WarperIsNotAvailableForRenting",
    type: "error",
  },
  {
    inputs: [],
    name: "__availabilityPeriodEnd",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "__availabilityPeriodRange",
    outputs: [
      {
        internalType: "uint32",
        name: "availabilityPeriodStart",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "availabilityPeriodEnd",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "__availabilityPeriodStart",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IAvailabilityPeriodMechanics__factory {
  static readonly abi = _abi;
  static createInterface(): IAvailabilityPeriodMechanicsInterface {
    return new utils.Interface(_abi) as IAvailabilityPeriodMechanicsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAvailabilityPeriodMechanics {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IAvailabilityPeriodMechanics;
  }
}
