/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface AssetsInterface extends ethers.utils.Interface {
  functions: {
    "ASSET_ID_TYPEHASH()": FunctionFragment;
    "ASSET_TYPEHASH()": FunctionFragment;
    "ERC1155()": FunctionFragment;
    "ERC721()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "ASSET_ID_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ASSET_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ERC1155", values?: undefined): string;
  encodeFunctionData(functionFragment: "ERC721", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "ASSET_ID_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ASSET_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ERC1155", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ERC721", data: BytesLike): Result;

  events: {};
}

export class Assets extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: AssetsInterface;

  functions: {
    ASSET_ID_TYPEHASH(overrides?: CallOverrides): Promise<[string]>;

    ASSET_TYPEHASH(overrides?: CallOverrides): Promise<[string]>;

    ERC1155(overrides?: CallOverrides): Promise<[string]>;

    ERC721(overrides?: CallOverrides): Promise<[string]>;
  };

  ASSET_ID_TYPEHASH(overrides?: CallOverrides): Promise<string>;

  ASSET_TYPEHASH(overrides?: CallOverrides): Promise<string>;

  ERC1155(overrides?: CallOverrides): Promise<string>;

  ERC721(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    ASSET_ID_TYPEHASH(overrides?: CallOverrides): Promise<string>;

    ASSET_TYPEHASH(overrides?: CallOverrides): Promise<string>;

    ERC1155(overrides?: CallOverrides): Promise<string>;

    ERC721(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    ASSET_ID_TYPEHASH(overrides?: CallOverrides): Promise<BigNumber>;

    ASSET_TYPEHASH(overrides?: CallOverrides): Promise<BigNumber>;

    ERC1155(overrides?: CallOverrides): Promise<BigNumber>;

    ERC721(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    ASSET_ID_TYPEHASH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ASSET_TYPEHASH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ERC1155(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ERC721(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
