/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IRentalPeriodMechanicsInterface extends ethers.utils.Interface {
  functions: {
    "__maxRentalPeriod()": FunctionFragment;
    "__minRentalPeriod()": FunctionFragment;
    "__rentalPeriodRange()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "__maxRentalPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "__minRentalPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "__rentalPeriodRange",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "__maxRentalPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "__minRentalPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "__rentalPeriodRange",
    data: BytesLike
  ): Result;

  events: {};
}

export class IRentalPeriodMechanics extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IRentalPeriodMechanicsInterface;

  functions: {
    __maxRentalPeriod(overrides?: CallOverrides): Promise<[number]>;

    __minRentalPeriod(overrides?: CallOverrides): Promise<[number]>;

    __rentalPeriodRange(
      overrides?: CallOverrides
    ): Promise<
      [number, number] & { minRentalPeriod: number; maxRentalPeriod: number }
    >;
  };

  __maxRentalPeriod(overrides?: CallOverrides): Promise<number>;

  __minRentalPeriod(overrides?: CallOverrides): Promise<number>;

  __rentalPeriodRange(
    overrides?: CallOverrides
  ): Promise<
    [number, number] & { minRentalPeriod: number; maxRentalPeriod: number }
  >;

  callStatic: {
    __maxRentalPeriod(overrides?: CallOverrides): Promise<number>;

    __minRentalPeriod(overrides?: CallOverrides): Promise<number>;

    __rentalPeriodRange(
      overrides?: CallOverrides
    ): Promise<
      [number, number] & { minRentalPeriod: number; maxRentalPeriod: number }
    >;
  };

  filters: {};

  estimateGas: {
    __maxRentalPeriod(overrides?: CallOverrides): Promise<BigNumber>;

    __minRentalPeriod(overrides?: CallOverrides): Promise<BigNumber>;

    __rentalPeriodRange(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    __maxRentalPeriod(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    __minRentalPeriod(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    __rentalPeriodRange(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
