name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & test (node ${{ matrix.node }}, ${{ matrix.os }})

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [ '14', '16' ]
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Unit tests
        run: yarn test

      - name: Integration tests
        run: yarn test:integration

  publish_docs:
    name: Publish Docs
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Generate docs
        run: yarn docs

      - name: Deploy docs 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: docs # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
