name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & test (node ${{ matrix.node }}, ${{ matrix.os }})

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [ '14', '16' ]
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Unit tests
        run: yarn test

      - name: Integration tests
        run: yarn test:integration
